name: Tests Job

on:
  workflow_call:

env:
  NODE_ENV: test
  JWT_SECRET: minhachavesecretadePELOMENOS32caracteres
  COOKIE_SECRET: outrachavesecretadePELOMENOS32caracteres
  DATABASE_URL: postgresql://docker:docker@localhost:5432/test_db
  BETTER_AUTH_SECRET: sua-chave-super-secreta-com-pelo-menos-32-caracteres
  BETTER_AUTH_URL: http://localhost:3100
  REDIS_HOST: localhost
  REDIS_PORT: 6379

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install

      - run: pnpm lint

  unit-tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports: ['6379:6379']

      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: test_db
        ports: ['5432:5432']

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install

      - run: pnpm db:push

      - run: pnpm test

  e2e-tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports: ['6379:6379']

      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: test_db
        ports: ['5432:5432']

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install

      - run: pnpm db:push

      - run: pnpm test:e2e
